# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad0e6255c6726fc4847c6278ff7ed2ccd7323eff7b084316f19e7ee3173f1a9b90bba3bb20ed512bce8741fce976245a54019306fa127bc5dc61b74d1655910

test:
  secret_key_base: ff1cb25b4c5904601d025ccff9576aff6b441442fdf14c07294962e6879ae02abf06a5f2d6fc4622e472e7cf9ade04b80a2bac374a150452bbe1c01c74ad65cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
